import { Arimo } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FirefliesBg from "./components/FirefliesBg.jsx";

const arimo = Arimo({ subsets: ["latin"], variable: "--font-arimo" });

export const metadata = {
  title: "Fatima's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={clsx(
          arimo.variable,
          "bg-background text-foreground font-arimo"
        )}
      >
        {children}
        <FirefliesBg />
      </body>
    </html>
  );
}
