/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tara.Hayes (https://sketchfab.com/Tara.Hayes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/witch-hat-0b2f058f76d74361a4640011ed8f9c26
Title: Witch Hat
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Hat(props) {
  const { nodes, materials } = useGLTF("/models/witch-hat.glb");

  const modelRef = useRef();

  useFrame((state) => {
    // move the hat up and down on the y-axis
    modelRef.current.position.y = Math.sin(state.clock.elapsedTime) * 0.2;
  })

  return (
    <group
      {...props}
      dispose={null}
      scale={[0.2, 0.2, 0.2]}
      position={[2.3, 0, 0]}
      rotation={[0, 0.5, 0]}
      ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pHelix4_lambert13_0.geometry}
        material={materials.lambert13}
        position={[-14.595, 0.241, -0.004]}
        rotation={[0, -0.047, 0]}
        scale={[1.151, 0.703, 1.151]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube3_lambert6_0.geometry}
        material={materials.lambert6}
        position={[-16.753, 2.452, 2.475]}
        rotation={[0.094, 0.919, 0.881]}
        scale={[0.759, 0.056, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube13_lambert5_0.geometry}
        material={materials.lambert5}
        position={[-12.137, 3.206, -0.728]}
        rotation={[0.838, 0.586, -1.389]}
        scale={[0.914, 0.074, 1.128]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube9_lambert2_0.geometry}
        material={materials.lambert2}
        position={[-13.932, 3.123, 8.839]}
        rotation={[-0.712, -1.09, -0.869]}
        scale={0.955}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder7_lambert10_0.geometry}
        material={materials.lambert10}
        position={[-17.12, 4.21, -0.392]}
        scale={0.442}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder9_lambert9_0.geometry}
        material={materials.lambert9}
        position={[-14.595, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube11_lambert3_0.geometry}
        material={materials.lambert3}
        position={[-12.015, 3.248, 1.371]}
        rotation={[-1.288, -0.953, -0.459]}
        scale={[1, 0.032, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube5_lambert4_0.geometry}
        material={materials.lambert4}
        position={[-17.695, 3.165, -0.075]}
        rotation={[-1.269, 0.828, 1.563]}
        scale={[0.645, 0.032, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder10_lambert11_0.geometry}
        material={materials.lambert11}
        position={[-17.143, 3.559, 0.214]}
        rotation={[0, 0, 0.242]}
        scale={0.381}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder11_lambert12_0.geometry}
        material={materials.lambert12}
        position={[-11.589, 3.451, 0.361]}
        scale={0.453}
      />
    </group>
  );
}

useGLTF.preload("/models/witch-hat.glb");
