/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Johan Pindeville (https://sketchfab.com/johanpindeville)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arcane-staff-of-resonance-wow-inspired-weapon-b2a8d6386cbd47939acadb94f637872a
Title: Arcane staff of Resonance - WOW inspired weapon
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Staff(props) {
  const { nodes, materials } = useGLTF(
    "/models/arcane_staff_of_resonance_-_wow_inspired_weapon.glb"
  );

  const modelRef = useRef();

  useFrame(() => {
    // Rotate the model in the y-axis at 0.01 radians per frame
    modelRef.current.rotation.y += 0.01;
  })

  return (
    <group
      {...props}
      dispose={null}
      scale={[0.33, 0.33, 0.33]}
      position={[0, -1.3, 0]}
      ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface704_syaff_lambert_wapen_0.geometry}
        material={materials.syaff_lambert_wapen}
      />
    </group>
  );
}

useGLTF.preload("/models/arcane_staff_of_resonance_-_wow_inspired_weapon.glb");
