/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ScarletJadeDream (https://sketchfab.com/ScarletJadeDream)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/elaina-the-witchs-journeysummerwhitedress-216ade78547a483fa055b15dae0c4ab0
Title: Elaina - The Witch's Journey(SummerWhiteDress)
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Witch(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/witch2-transformed.glb"
  );

  const modelRef = useRef();
  useFrame((state, delta, xrFrame) => {
    // to move the model up and down
    // the elapsedTime increases by 0.016 every frame 
    // Math.sin will return a value between -1 and 1
    modelRef.current.position.y = Math.sin(state.clock.elapsedTime) * 0.2;
  });


  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[0, -2, 0]}
      scale={[0.9, 0.9, 0.9]}
      rotation={[0.1, -0.3, 0]}
    >
      <group name="Sketchfab_Scene" ref={modelRef}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_895"
          geometry={nodes.Object_895.geometry}
          material={materials.Body}
          skeleton={nodes.Object_895.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_896"
          geometry={nodes.Object_896.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_896.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_898"
          geometry={nodes.Object_898.geometry}
          material={materials.Eyebrow}
          skeleton={nodes.Object_898.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_900"
          geometry={nodes.Object_900.geometry}
          material={materials.material}
          skeleton={nodes.Object_900.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_902"
          geometry={nodes.Object_902.geometry}
          material={materials.Body}
          skeleton={nodes.Object_902.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_903"
          geometry={nodes.Object_903.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_903.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_905"
          geometry={nodes.Object_905.geometry}
          material={materials.material}
          skeleton={nodes.Object_905.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_907"
          geometry={nodes.Object_907.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_907.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_908"
          geometry={nodes.Object_908.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_908.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_910"
          geometry={nodes.Object_910.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_910.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_911"
          geometry={nodes.Object_911.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_911.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_913"
          geometry={nodes.Object_913.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_913.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_914"
          geometry={nodes.Object_914.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_914.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_916"
          geometry={nodes.Object_916.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_916.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_917"
          geometry={nodes.Object_917.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_917.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_919"
          geometry={nodes.Object_919.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_919.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_920"
          geometry={nodes.Object_920.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_920.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_922"
          geometry={nodes.Object_922.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_922.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_923"
          geometry={nodes.Object_923.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_923.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_925"
          geometry={nodes.Object_925.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_925.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_926"
          geometry={nodes.Object_926.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_926.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_928"
          geometry={nodes.Object_928.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_928.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_929"
          geometry={nodes.Object_929.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_929.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_931"
          geometry={nodes.Object_931.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_931.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_932"
          geometry={nodes.Object_932.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_932.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_934"
          geometry={nodes.Object_934.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_934.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_935"
          geometry={nodes.Object_935.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_935.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_937"
          geometry={nodes.Object_937.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_937.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_938"
          geometry={nodes.Object_938.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_938.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_940"
          geometry={nodes.Object_940.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_940.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_941"
          geometry={nodes.Object_941.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_941.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_943"
          geometry={nodes.Object_943.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_943.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_944"
          geometry={nodes.Object_944.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_944.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_946"
          geometry={nodes.Object_946.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_946.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_947"
          geometry={nodes.Object_947.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_947.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_949"
          geometry={nodes.Object_949.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_949.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_950"
          geometry={nodes.Object_950.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_950.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_952"
          geometry={nodes.Object_952.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_952.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_953"
          geometry={nodes.Object_953.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_953.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_955"
          geometry={nodes.Object_955.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_955.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_956"
          geometry={nodes.Object_956.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_956.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_958"
          geometry={nodes.Object_958.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_958.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_959"
          geometry={nodes.Object_959.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_959.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_961"
          geometry={nodes.Object_961.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_961.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_962"
          geometry={nodes.Object_962.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_962.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_964"
          geometry={nodes.Object_964.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_964.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_965"
          geometry={nodes.Object_965.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_965.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_967"
          geometry={nodes.Object_967.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_967.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_968"
          geometry={nodes.Object_968.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_968.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_970"
          geometry={nodes.Object_970.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_970.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_971"
          geometry={nodes.Object_971.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_971.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_973"
          geometry={nodes.Object_973.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_973.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_974"
          geometry={nodes.Object_974.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_974.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_976"
          geometry={nodes.Object_976.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_976.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_977"
          geometry={nodes.Object_977.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_977.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_979"
          geometry={nodes.Object_979.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_979.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_980"
          geometry={nodes.Object_980.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_980.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_982"
          geometry={nodes.Object_982.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_982.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_983"
          geometry={nodes.Object_983.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_983.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_985"
          geometry={nodes.Object_985.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_985.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_986"
          geometry={nodes.Object_986.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_986.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_988"
          geometry={nodes.Object_988.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_988.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_989"
          geometry={nodes.Object_989.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_989.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_991"
          geometry={nodes.Object_991.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_991.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_992"
          geometry={nodes.Object_992.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_992.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_994"
          geometry={nodes.Object_994.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_994.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_995"
          geometry={nodes.Object_995.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_995.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_997"
          geometry={nodes.Object_997.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_997.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_998"
          geometry={nodes.Object_998.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_998.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1000"
          geometry={nodes.Object_1000.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1000.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1001"
          geometry={nodes.Object_1001.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1001.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1003"
          geometry={nodes.Object_1003.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1003.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1004"
          geometry={nodes.Object_1004.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1004.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1006"
          geometry={nodes.Object_1006.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1006.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1007"
          geometry={nodes.Object_1007.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1007.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1009"
          geometry={nodes.Object_1009.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1009.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1010"
          geometry={nodes.Object_1010.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1010.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1012"
          geometry={nodes.Object_1012.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1012.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1013"
          geometry={nodes.Object_1013.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1013.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1015"
          geometry={nodes.Object_1015.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1015.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1016"
          geometry={nodes.Object_1016.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1016.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1018"
          geometry={nodes.Object_1018.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1018.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1019"
          geometry={nodes.Object_1019.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1019.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1021"
          geometry={nodes.Object_1021.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1021.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1022"
          geometry={nodes.Object_1022.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1022.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1024"
          geometry={nodes.Object_1024.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1024.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1025"
          geometry={nodes.Object_1025.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1025.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1027"
          geometry={nodes.Object_1027.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1027.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1028"
          geometry={nodes.Object_1028.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1028.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1030"
          geometry={nodes.Object_1030.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1030.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1031"
          geometry={nodes.Object_1031.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1031.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1033"
          geometry={nodes.Object_1033.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1033.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1034"
          geometry={nodes.Object_1034.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1034.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1036"
          geometry={nodes.Object_1036.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1036.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1037"
          geometry={nodes.Object_1037.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1037.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1039"
          geometry={nodes.Object_1039.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1039.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1040"
          geometry={nodes.Object_1040.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1040.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1042"
          geometry={nodes.Object_1042.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1042.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1043"
          geometry={nodes.Object_1043.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1043.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1045"
          geometry={nodes.Object_1045.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1045.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1046"
          geometry={nodes.Object_1046.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1046.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1048"
          geometry={nodes.Object_1048.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1048.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1049"
          geometry={nodes.Object_1049.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1049.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1051"
          geometry={nodes.Object_1051.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1051.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1052"
          geometry={nodes.Object_1052.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1052.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1054"
          geometry={nodes.Object_1054.geometry}
          material={materials.Hair}
          skeleton={nodes.Object_1054.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1055"
          geometry={nodes.Object_1055.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1055.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1057"
          geometry={nodes.Object_1057.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1057.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1058"
          geometry={nodes.Object_1058.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1058.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1060"
          geometry={nodes.Object_1060.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1060.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1061"
          geometry={nodes.Object_1061.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1061.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1063"
          geometry={nodes.Object_1063.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1063.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1064"
          geometry={nodes.Object_1064.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1064.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1066"
          geometry={nodes.Object_1066.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1066.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1067"
          geometry={nodes.Object_1067.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1067.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1069"
          geometry={nodes.Object_1069.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1069.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1070"
          geometry={nodes.Object_1070.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1070.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1072"
          geometry={nodes.Object_1072.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1072.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1073"
          geometry={nodes.Object_1073.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1073.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1075"
          geometry={nodes.Object_1075.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1075.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1076"
          geometry={nodes.Object_1076.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1076.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1078"
          geometry={nodes.Object_1078.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1078.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1079"
          geometry={nodes.Object_1079.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1079.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1081"
          geometry={nodes.Object_1081.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1081.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1082"
          geometry={nodes.Object_1082.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1082.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1084"
          geometry={nodes.Object_1084.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1084.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1085"
          geometry={nodes.Object_1085.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1085.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1087"
          geometry={nodes.Object_1087.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1087.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1088"
          geometry={nodes.Object_1088.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1088.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1090"
          geometry={nodes.Object_1090.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1090.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1091"
          geometry={nodes.Object_1091.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1091.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1093"
          geometry={nodes.Object_1093.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1093.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1094"
          geometry={nodes.Object_1094.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1094.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1096"
          geometry={nodes.Object_1096.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1096.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1097"
          geometry={nodes.Object_1097.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1097.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1099"
          geometry={nodes.Object_1099.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1099.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1100"
          geometry={nodes.Object_1100.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1100.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1102"
          geometry={nodes.Object_1102.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1102.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1103"
          geometry={nodes.Object_1103.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1103.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1105"
          geometry={nodes.Object_1105.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1105.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1106"
          geometry={nodes.Object_1106.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1106.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1108"
          geometry={nodes.Object_1108.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1108.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1109"
          geometry={nodes.Object_1109.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1109.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1111"
          geometry={nodes.Object_1111.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1111.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1112"
          geometry={nodes.Object_1112.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1112.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1114"
          geometry={nodes.Object_1114.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1114.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1115"
          geometry={nodes.Object_1115.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1115.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1117"
          geometry={nodes.Object_1117.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1117.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1118"
          geometry={nodes.Object_1118.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1118.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1120"
          geometry={nodes.Object_1120.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1120.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1121"
          geometry={nodes.Object_1121.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1121.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1123"
          geometry={nodes.Object_1123.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1123.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1124"
          geometry={nodes.Object_1124.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1124.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1126"
          geometry={nodes.Object_1126.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1126.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1127"
          geometry={nodes.Object_1127.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1127.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1129"
          geometry={nodes.Object_1129.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1129.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1130"
          geometry={nodes.Object_1130.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1130.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1132"
          geometry={nodes.Object_1132.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1132.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1133"
          geometry={nodes.Object_1133.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1133.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1135"
          geometry={nodes.Object_1135.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1135.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1136"
          geometry={nodes.Object_1136.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1136.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1138"
          geometry={nodes.Object_1138.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1138.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1139"
          geometry={nodes.Object_1139.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1139.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1141"
          geometry={nodes.Object_1141.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1141.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1142"
          geometry={nodes.Object_1142.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1142.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1144"
          geometry={nodes.Object_1144.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1144.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1145"
          geometry={nodes.Object_1145.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1145.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1147"
          geometry={nodes.Object_1147.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1147.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1148"
          geometry={nodes.Object_1148.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1148.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1150"
          geometry={nodes.Object_1150.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1150.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1151"
          geometry={nodes.Object_1151.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1151.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1153"
          geometry={nodes.Object_1153.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1153.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1154"
          geometry={nodes.Object_1154.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1154.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1156"
          geometry={nodes.Object_1156.geometry}
          material={materials.material_7}
          skeleton={nodes.Object_1156.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1157"
          geometry={nodes.Object_1157.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1157.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1159"
          geometry={nodes.Object_1159.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1159.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1160"
          geometry={nodes.Object_1160.geometry}
          material={materials.Overcoat_B}
          skeleton={nodes.Object_1160.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1161"
          geometry={nodes.Object_1161.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1161.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1163"
          geometry={nodes.Object_1163.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1163.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1164"
          geometry={nodes.Object_1164.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1164.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1166"
          geometry={nodes.Object_1166.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1166.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1167"
          geometry={nodes.Object_1167.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1167.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1169"
          geometry={nodes.Object_1169.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1169.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1170"
          geometry={nodes.Object_1170.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1170.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1172"
          geometry={nodes.Object_1172.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1172.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1173"
          geometry={nodes.Object_1173.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1173.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1175"
          geometry={nodes.Object_1175.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1175.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1176"
          geometry={nodes.Object_1176.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1176.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1178"
          geometry={nodes.Object_1178.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1178.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1179"
          geometry={nodes.Object_1179.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1179.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1181"
          geometry={nodes.Object_1181.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1181.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1182"
          geometry={nodes.Object_1182.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1182.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1184"
          geometry={nodes.Object_1184.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1184.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1185"
          geometry={nodes.Object_1185.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1185.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1187"
          geometry={nodes.Object_1187.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1187.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1188"
          geometry={nodes.Object_1188.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1188.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1190"
          geometry={nodes.Object_1190.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1190.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1191"
          geometry={nodes.Object_1191.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1191.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1193"
          geometry={nodes.Object_1193.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1193.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1194"
          geometry={nodes.Object_1194.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1194.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1196"
          geometry={nodes.Object_1196.geometry}
          material={materials.Overcoat_F}
          skeleton={nodes.Object_1196.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1197"
          geometry={nodes.Object_1197.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1197.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1199"
          geometry={nodes.Object_1199.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1199.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1200"
          geometry={nodes.Object_1200.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1200.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1202"
          geometry={nodes.Object_1202.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1202.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1203"
          geometry={nodes.Object_1203.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1203.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1205"
          geometry={nodes.Object_1205.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1205.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1206"
          geometry={nodes.Object_1206.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1206.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1208"
          geometry={nodes.Object_1208.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1208.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1209"
          geometry={nodes.Object_1209.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1209.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1211"
          geometry={nodes.Object_1211.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1211.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1212"
          geometry={nodes.Object_1212.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1212.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1214"
          geometry={nodes.Object_1214.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1214.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1215"
          geometry={nodes.Object_1215.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1215.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1217"
          geometry={nodes.Object_1217.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1217.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1218"
          geometry={nodes.Object_1218.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1218.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1220"
          geometry={nodes.Object_1220.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1220.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1221"
          geometry={nodes.Object_1221.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1221.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1223"
          geometry={nodes.Object_1223.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1223.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1224"
          geometry={nodes.Object_1224.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1224.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1226"
          geometry={nodes.Object_1226.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1226.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1227"
          geometry={nodes.Object_1227.geometry}
          material={materials.WhiteDress_B}
          skeleton={nodes.Object_1227.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1228"
          geometry={nodes.Object_1228.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1228.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1230"
          geometry={nodes.Object_1230.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1230.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1231"
          geometry={nodes.Object_1231.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1231.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1233"
          geometry={nodes.Object_1233.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1233.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1234"
          geometry={nodes.Object_1234.geometry}
          material={materials.WhiteDress_B}
          skeleton={nodes.Object_1234.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1235"
          geometry={nodes.Object_1235.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1235.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1237"
          geometry={nodes.Object_1237.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1237.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1238"
          geometry={nodes.Object_1238.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1238.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1240"
          geometry={nodes.Object_1240.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1240.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1241"
          geometry={nodes.Object_1241.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1241.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1243"
          geometry={nodes.Object_1243.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1243.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1244"
          geometry={nodes.Object_1244.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1244.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1246"
          geometry={nodes.Object_1246.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1246.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1247"
          geometry={nodes.Object_1247.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1247.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1249"
          geometry={nodes.Object_1249.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1249.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1250"
          geometry={nodes.Object_1250.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1250.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1252"
          geometry={nodes.Object_1252.geometry}
          material={materials.WhiteDress_F}
          skeleton={nodes.Object_1252.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_1253"
          geometry={nodes.Object_1253.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_1253.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group name="cs_grp" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="cs_solid_triangle"
            position={[-0.277, -0.053, -0.474]}
            rotation={[Math.PI / 2, -1.571, 0]}
            scale={0.225}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/witch2-transformed.glb");
